
package VIEW;

import CONTROLLER.AddProductCon;
import CONTROLLER.ShowProductCon;
import MODEL.Television;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class AddTelevisionView extends javax.swing.JFrame {

    /**
     * Creates new form AddTelevisionView1
     */
    public AddTelevisionView() {
        initComponents();
        //display on the center of the screen
        this.setLocationRelativeTo(null);
        //list of the models of the television
        List<String> items=new ArrayList<String>();
        //get the list of the models from the database
        items = television.getListaTel("Television");
        if(items.isEmpty())
            //message that the list is empty
            JOptionPane.showMessageDialog(null,"No list of models have found!Please try again! ");
        //the first element of the list
        items.add(0, "MODELS...");
        //copy the list to the combo box
        for(String a:items)
            jComboBoxModelTelevision.addItem(a);
    }
    
    //instances of Controllers for the call of their methods
    AddProductCon updateItem=new AddProductCon();
    ShowProductCon television=new ShowProductCon();
    //the choice of the ComboBox
    private String jboxmodelChoice=null;
    private String jboxmodel=null;
    private String marka=null;
    //the model and the brand of the product
    private String modelT=null;
    private String brandT=null;
    //initialization of the variable for the control of the ComboBox
    private boolean empty=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButtonAddItem = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextModel = new javax.swing.JTextField();
        jTextBrand = new javax.swing.JTextField();
        jTextScreen = new javax.swing.JTextField();
        jTextSharpness = new javax.swing.JTextField();
        jTextFrequency = new javax.swing.JTextField();
        jTextSmart = new javax.swing.JTextField();
        jTextYear = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextQuantity = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxModelTelevision = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD TELEVISION ITEM");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel7.setText("Frequency*:");

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel9.setText("Sharpness*:");

        jLabel17.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel17.setText("Year*:");

        jLabel18.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel18.setText("Screen*:");
        jLabel18.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel20.setText("Smart*:");

        jLabel21.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel21.setText("Price*:");

        jLabel22.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel22.setText("Brand*:");
        jLabel22.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("TELEVISION");

        jButtonAddItem.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAddItem.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButtonAddItem.setText("ADD");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(255, 255, 0));
        jButtonReset.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextModel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jTextBrand.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jTextScreen.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextScreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextScreenKeyTyped(evt);
            }
        });

        jTextSharpness.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jTextFrequency.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextFrequency.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFrequencyKeyTyped(evt);
            }
        });

        jTextSmart.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextSmart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSmartKeyTyped(evt);
            }
        });

        jTextYear.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextYearKeyTyped(evt);
            }
        });

        jTextPrice.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPriceKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("**required fields for add and delete item  ");

        jLabel24.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel24.setText("Quantity**:");

        jTextQuantity.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextQuantityKeyTyped(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("*required fields for add item  ");

        jComboBoxModelTelevision.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jComboBoxModelTelevision.setToolTipText("");
        jComboBoxModelTelevision.setAutoscrolls(true);
        jComboBoxModelTelevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelTelevisionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel10.setText("Brand & model**:");

        jLabel15.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel15.setText("Or write model*:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextSmart, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFrequency, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextSharpness, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextScreen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextModel)
                            .addComponent(jTextQuantity)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxModelTelevision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModelTelevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSharpness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSmart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonAddItem))
                .addGap(72, 72, 72))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPriceKeyTyped
        //check if the input of the user is a digit or (.) for the decimals
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='.')||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit or decimal point(.)");
            evt.consume();
        }
    }//GEN-LAST:event_jTextPriceKeyTyped

    private void jTextYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextYearKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextYearKeyTyped

    private void jTextFrequencyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFrequencyKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextFrequencyKeyTyped

    private void jTextScreenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextScreenKeyTyped
        //check if the input of the user is a digit or (.) for the decimals
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='.')||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit or decimal point(.)");
            evt.consume();
        }
    }//GEN-LAST:event_jTextScreenKeyTyped

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        //reset all the fields
        jTextModel.setText(null);
        jTextBrand.setText(null);
        jTextScreen.setText(null);
        jTextFrequency.setText(null);
        jTextSharpness.setText(null);
        jTextSmart.setText(null);
        jTextYear.setText(null);
        jTextPrice.setText(null);
        jTextQuantity.setText(null);
        empty=false;
        modelT=null;
        marka=null;
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextSmartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSmartKeyTyped
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert '0' if it is not SMART or any other number if it is SMART");
            evt.consume();
        }
    }//GEN-LAST:event_jTextSmartKeyTyped
    //add a model
    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        //if the model is already in the database(some fields are null)
        if(jTextModel.getText().isEmpty())
        {
            empty=true;
            //get the choice of the combo box
            jComboBoxModelTelevisionActionPerformed(evt);
            //the model and the brand
            modelT=jboxmodel;
            brandT=marka;
            //the quantity from the input
            String quantityT=jTextQuantity.getText();
            //if the field quantity is null
            if(jTextQuantity.getText().isEmpty())
                JOptionPane.showMessageDialog(null,"please fill the quantity");
            else
            {
                //find the model from the database
                Television tele=(Television) television.getChoosenModelTel(modelT, "Television");
                //inform the user the quantity of the model and ask if he/she wants to continue
                int answer = JOptionPane.showConfirmDialog(this,"The item(s) of this model are "+tele.getQuantity()
                +"\n"+"Do you want to continue?","Confirmation",  JOptionPane.YES_NO_OPTION);
                if (answer == JOptionPane.YES_OPTION)
                {
                    //update the quantity of the model in the database
                    if(updateItem.updateAddTelevisionCon(modelT, quantityT))
                    {
                        JOptionPane.showMessageDialog(null,"The item has been added in the database");                   
                    }
                    else 
                        JOptionPane.showMessageDialog(null,"The item has not been added in the database. Please try again!");
                }
                else 
                {
                    JOptionPane.showMessageDialog(this, "Please try again!");
                }  
            }
        }   
        //if it is a new entry in the database
        else
        { 
            //save all the inputs of the user
            modelT=jTextModel.getText();
            brandT=jTextBrand.getText();
            String screenT=jTextScreen.getText();
            String frequencyT=jTextFrequency.getText();
            String sharpnessT=jTextSharpness.getText();
            String smartT=jTextSmart.getText();
            String yearT=jTextYear.getText();
            String priceT=jTextPrice.getText();
            String quantityT=jTextQuantity.getText();
            //check if all the fields are filled
            boolean emptyError = updateItem.nullMessageTel(modelT, brandT, sharpnessT, priceT, screenT, frequencyT, smartT, yearT,quantityT);
            if(emptyError)
                JOptionPane.showMessageDialog(null,"please fill in all the required fields");
            else
            {
                //update the database with the new model
                if(updateItem.addTelevisionCon(modelT, brandT, sharpnessT, priceT, screenT, frequencyT, smartT, yearT,quantityT))
                {
                    JOptionPane.showMessageDialog(null,"The item has been added in the database");
                }
                else 
                    JOptionPane.showMessageDialog(null,"The item has not been added in the database. Please try again!");
            }            
        }
        //reset the fields
        jButtonResetActionPerformed(evt);        
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jTextQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextQuantityKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextQuantityKeyTyped
    //delete a model
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        empty=true;
        //get the choice of the combo box
        jComboBoxModelTelevisionActionPerformed(evt);
        //get the model and the quantity inputs
        modelT=jboxmodel;
        String quantityT=jTextQuantity.getText();
        //find the model from the database
        Television tele=(Television) television.getChoosenModelTel(modelT, "Television");
        //inform the user the quantity of the model and ask if he/she wants to continue
        int reply = JOptionPane.showConfirmDialog(this,"The item(s) of this model are "+tele.getQuantity()
                +"\n"+"Do you want to continue?","Confirmation",  JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) 
        {
            //update the quantity of the model in the database
            if(updateItem.updateTelevisionCon(modelT, quantityT))
            {
                JOptionPane.showMessageDialog(this, "the database has been updated");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "the model has not been found or there are not so many item(s) of it.Please try again!");
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Please try again!");
        } 
        //reset the fields
        jButtonResetActionPerformed(evt);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxModelTelevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelTelevisionActionPerformed
        if(empty)
        {
            //the choice of the user from the combo box
            jboxmodelChoice=jComboBoxModelTelevision.getSelectedItem().toString();
            //if the user haven t choose a model
            if(jboxmodelChoice=="MODELS...")
            {
                //display a message to choose a model
                JOptionPane.showMessageDialog(null,"Please choose a model");
                jboxmodelChoice=null;
                //reset the fields
                jButtonResetActionPerformed(evt);
            }
            else
            {
                //separate the string,first is the brand second is the model
                String[] s=jboxmodelChoice.split(":");
                marka=s[0];
                jboxmodel=s[1];
            }
        }
    }//GEN-LAST:event_jComboBoxModelTelevisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTelevisionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTelevisionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTelevisionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTelevisionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTelevisionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxModelTelevision;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBrand;
    private javax.swing.JTextField jTextFrequency;
    private javax.swing.JTextField jTextModel;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextScreen;
    private javax.swing.JTextField jTextSharpness;
    private javax.swing.JTextField jTextSmart;
    private javax.swing.JTextField jTextYear;
    // End of variables declaration//GEN-END:variables
}
