
package VIEW;

import static VIEW.Login.ipallilos;
import javax.swing.JOptionPane;

public class MenuGui extends javax.swing.JFrame {

    /**
     * Creates new form MenuGui
     */
    public MenuGui() {
        initComponents();
        //dislpay on the center of the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCategories = new javax.swing.JMenu();
        jMenuTelevision = new javax.swing.JMenuItem();
        jMenuCamera = new javax.swing.JMenuItem();
        jMenuMobile = new javax.swing.JMenuItem();
        jMenuLaptop = new javax.swing.JMenuItem();
        jMenuOrder = new javax.swing.JMenu();
        jMenuCreateOrder = new javax.swing.JMenuItem();
        jMenuShowOrder = new javax.swing.JMenuItem();
        jMenuStatistics = new javax.swing.JMenu();
        jMenuShowStatistics = new javax.swing.JMenuItem();
        jMenuSale = new javax.swing.JMenu();
        jMenuCreateSale = new javax.swing.JMenuItem();
        jMenuShowSale = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenuStock = new javax.swing.JMenu();
        jMenuAddItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to TECHSTORE");
        jLabel2.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business-computer-connection-contemporary-450035.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(657, 408));
        jLabel1.setMinimumSize(new java.awt.Dimension(657, 408));
        jLabel1.setPreferredSize(new java.awt.Dimension(657, 408));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jMenuCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_order_2639879.png"))); // NOI18N
        jMenuCategories.setText("CATEGORIES");
        jMenuCategories.setToolTipText("");
        jMenuCategories.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenuTelevision.setBackground(new java.awt.Color(153, 153, 255));
        jMenuTelevision.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuTelevision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_12_2135927.png"))); // NOI18N
        jMenuTelevision.setText("TELEVISION");
        jMenuTelevision.setToolTipText("");
        jMenuTelevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTelevisionActionPerformed(evt);
            }
        });
        jMenuCategories.add(jMenuTelevision);

        jMenuCamera.setBackground(new java.awt.Color(255, 102, 102));
        jMenuCamera.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_25.Camera-Front_290125.png"))); // NOI18N
        jMenuCamera.setText("CAMERA");
        jMenuCamera.setToolTipText("");
        jMenuCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCameraActionPerformed(evt);
            }
        });
        jMenuCategories.add(jMenuCamera);

        jMenuMobile.setBackground(new java.awt.Color(255, 255, 153));
        jMenuMobile.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_icons_mobile_1564515.png"))); // NOI18N
        jMenuMobile.setText("MOBILE");
        jMenuMobile.setToolTipText("");
        jMenuMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMobileActionPerformed(evt);
            }
        });
        jMenuCategories.add(jMenuMobile);

        jMenuLaptop.setBackground(new java.awt.Color(153, 255, 153));
        jMenuLaptop.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuLaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_Laptop_3428069.png"))); // NOI18N
        jMenuLaptop.setText("LAPTOP");
        jMenuLaptop.setToolTipText("");
        jMenuLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaptopActionPerformed(evt);
            }
        });
        jMenuCategories.add(jMenuLaptop);

        jMenuBar1.add(jMenuCategories);

        jMenuOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_order-history_49596.png"))); // NOI18N
        jMenuOrder.setText("ORDER");
        jMenuOrder.setToolTipText("");
        jMenuOrder.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenuCreateOrder.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuCreateOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_gtk-sort-descending_20550.png"))); // NOI18N
        jMenuCreateOrder.setText("CREATE ORDER");
        jMenuCreateOrder.setToolTipText("");
        jMenuCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateOrderActionPerformed(evt);
            }
        });
        jMenuOrder.add(jMenuCreateOrder);

        jMenuShowOrder.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuShowOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_stock_reverse-order_94695.png"))); // NOI18N
        jMenuShowOrder.setText("SHOW ORDER");
        jMenuShowOrder.setToolTipText("");
        jMenuShowOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuShowOrderActionPerformed(evt);
            }
        });
        jMenuOrder.add(jMenuShowOrder);

        jMenuBar1.add(jMenuOrder);

        jMenuStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder__76ui_2303181.png"))); // NOI18N
        jMenuStatistics.setText("STATISTICS");
        jMenuStatistics.setToolTipText("");
        jMenuStatistics.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenuShowStatistics.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuShowStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_Data-16_4203020.png"))); // NOI18N
        jMenuShowStatistics.setText("SHOW STATISTICS");
        jMenuShowStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuShowStatisticsActionPerformed(evt);
            }
        });
        jMenuStatistics.add(jMenuShowStatistics);

        jMenuBar1.add(jMenuStatistics);

        jMenuSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_cart-6_3338941.png"))); // NOI18N
        jMenuSale.setText("SALE");
        jMenuSale.setToolTipText("");
        jMenuSale.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenuCreateSale.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuCreateSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_cart-5_3338940.png"))); // NOI18N
        jMenuCreateSale.setText("CREATE SALE");
        jMenuCreateSale.setToolTipText("");
        jMenuCreateSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateSaleActionPerformed(evt);
            }
        });
        jMenuSale.add(jMenuCreateSale);

        jMenuShowSale.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuShowSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_business_finance_money-34_2784267.png"))); // NOI18N
        jMenuShowSale.setText("SHOW SALE");
        jMenuShowSale.setToolTipText("");
        jMenuShowSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuShowSaleActionPerformed(evt);
            }
        });
        jMenuSale.add(jMenuShowSale);

        jMenuBar1.add(jMenuSale);

        jMenuStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconfinder_Data-02_4203035.png"))); // NOI18N
        jMenuStock.setText("STOCK");
        jMenuStock.setToolTipText("");
        jMenuStock.setFocusable(false);
        jMenuStock.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jMenuAddItem.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jMenuAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-import-30.png"))); // NOI18N
        jMenuAddItem.setText("UPDATE STOCK");
        jMenuAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddItemActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuAddItem);

        jMenuBar1.add(jMenuStock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //display the camera view
    private void jMenuCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCameraActionPerformed
        new CameraView().setVisible(true);
    }//GEN-LAST:event_jMenuCameraActionPerformed
    //display the statistics
    private void jMenuShowStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuShowStatisticsActionPerformed
        //if the user is a product manager
        if(ipallilos.isIsProistamenos())
            new StatisticsShowView().setVisible(true);
        else
            JOptionPane.showMessageDialog(null,"you don t have the autherization for this function");
    }//GEN-LAST:event_jMenuShowStatisticsActionPerformed
    //display the order
    private void jMenuShowOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuShowOrderActionPerformed
        //if the user is a product manager
        if(ipallilos.isIsProistamenos())
            new OrderShowView().setVisible(true);
        else
            JOptionPane.showMessageDialog(null,"you don t have the autherization for this function");
    }//GEN-LAST:event_jMenuShowOrderActionPerformed
    //display update stock view
    private void jMenuAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddItemActionPerformed
        new UpdateStockView().setVisible(true);
    }//GEN-LAST:event_jMenuAddItemActionPerformed
    //display television view
    private void jMenuTelevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTelevisionActionPerformed
        new TelevisionView().setVisible(true);
    }//GEN-LAST:event_jMenuTelevisionActionPerformed
    //display mobile view
    private void jMenuMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMobileActionPerformed
        new MobileView().setVisible(true);
    }//GEN-LAST:event_jMenuMobileActionPerformed
    //display laptop view
    private void jMenuLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaptopActionPerformed
        new LaptopView().setVisible(true);
    }//GEN-LAST:event_jMenuLaptopActionPerformed
    //display the make of order view
    private void jMenuCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateOrderActionPerformed
        //if the user is a product manager
        if(ipallilos.isIsProistamenos())
            new OrderCreateView().setVisible(true);
        else
            JOptionPane.showMessageDialog(null,"you don t have the autherization for this function");
    }//GEN-LAST:event_jMenuCreateOrderActionPerformed
    //display the make of sale view
    private void jMenuCreateSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateSaleActionPerformed
        //if the user is an employee
        if(!ipallilos.isIsProistamenos())
            new SaleCreateView().setVisible(true);
        else
            JOptionPane.showMessageDialog(null,"only an employee can create a sale");
    }//GEN-LAST:event_jMenuCreateSaleActionPerformed
    //display the sale
    private void jMenuShowSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuShowSaleActionPerformed
        new SaleShowView().setVisible(true);
    }//GEN-LAST:event_jMenuShowSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuAddItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCamera;
    private javax.swing.JMenu jMenuCategories;
    private javax.swing.JMenuItem jMenuCreateOrder;
    private javax.swing.JMenuItem jMenuCreateSale;
    private javax.swing.JMenuItem jMenuLaptop;
    private javax.swing.JMenuItem jMenuMobile;
    private javax.swing.JMenu jMenuOrder;
    private javax.swing.JMenu jMenuSale;
    private javax.swing.JMenuItem jMenuShowOrder;
    private javax.swing.JMenuItem jMenuShowSale;
    private javax.swing.JMenuItem jMenuShowStatistics;
    private javax.swing.JMenu jMenuStatistics;
    private javax.swing.JMenuItem jMenuTelevision;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
