
package VIEW;

import MODEL.Order;
import CONTROLLER.OrderCon;
import MODEL.OrderString;
import MODEL.ProductManager;
import MODEL.User;
import static VIEW.Login.ipallilos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class OrderCreateView extends javax.swing.JFrame {

    /**
     * Creates new form ProductView
     */
    public OrderCreateView() {
        initComponents();
        //εμφάνιση στο κέντρο της οθόνης
        this.setLocationRelativeTo(null);
    }

    //αντικείμενο CONTROLLER που θα χρησιμοποιηθεί
    OrderCon ordercon=new OrderCon();
    //η επιλογή του πίνακα
    String jboxproduct;
    //η επιλογή του μοντέλου από το combobox
    String jboxmodel;
    //η επιλογή του μοντέλου από το textfield
    String jTextModel;
    //η επιλογή της μάρκας από το textfield
    String jTextBrand;
    //η τελική επιλογή του μοντέλου 
    String jmodel;
    //η επλογή από τη λίστα μοντέλων
    String jboxmodelChoice;
    //η μάρκα του επιλεγμένου μοντέλου
    String marka;
    //η ποσότητα του κάθε προιόντος που γίνεται παραγγελία
    String quantity;
    //η καταχ'ωρηση ενός προϊόντος
    String paraggelia;
    //Η λίστα με τα ονόματα των μοντέλων σε μια παραγγελία
    private ArrayList<OrderString> OrderModelList=new ArrayList<>();
    //η λίστα με τα μοντέλα σε μορφή string
    private ArrayList<String> OrderList=new ArrayList<>();
    //η λίστα του jTable
    DefaultTableModel lista;
    //λίστα με τα διεγραμμένα προίόντα με το όνομα του μοντέλου μόνο
    private ArrayList<String> deletedList=new ArrayList<>();
    //η τελικη λίστα με τα διεγραμμένα μοντέλα σε μορφή string
    private ArrayList<String> finaDeletedlList=new ArrayList<>();
    //μεταβλητή για την επαλήθευση της αποθήκευσης προϊόντος μιας παραγγελίας
    boolean saved=false;
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProduct = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jComboBoxModel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextWriteBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextItems = new javax.swing.JTextField();
        jTextWriteModel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREATE ORDER");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setName(""); // NOI18N

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel9.setText("CHOOSE A PRODUCT:");

        jComboBoxProduct.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jComboBoxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORY...", "TELEVISION", "CAMERA", "MOBILE", "LAPTOP" }));
        jComboBoxProduct.setToolTipText("");
        jComboBoxProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel10.setText("CHOOSE THE MODEL:");
        jLabel10.setToolTipText("");

        jTableOrder.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "BRAND", "MODEL", "QUANTITY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableOrder.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTableOrder);
        jTableOrder.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButtonAdd.setBackground(new java.awt.Color(0, 255, 0));
        jButtonAdd.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.setToolTipText("");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(0, 0, 255));
        jButtonSave.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jComboBoxModel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jComboBoxModel.setToolTipText("");
        jComboBoxModel.setAutoscrolls(true);
        jComboBoxModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel11.setText("OR WRITE THE BRAND:");
        jLabel11.setToolTipText("");

        jTextWriteBrand.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("ITEM(S):");

        jTextItems.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextItemsKeyTyped(evt);
            }
        });

        jTextWriteModel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel12.setText("WRITE THE MODEL:");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextWriteBrand)
                            .addComponent(jTextItems)
                            .addComponent(jTextWriteModel)))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextWriteBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextWriteModel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextItems, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Create an order...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelActionPerformed
        //μόνο εάν έχει αντικείμενα η λίστα του jComboBox με τα μοντέλα
        if(jComboBoxModel.getItemCount()>0)
        {
            //αποθήκευση της επολογής του χρήστη
            jboxmodelChoice=jComboBoxModel.getSelectedItem().toString();
            if(jboxmodelChoice=="MODELS...")
            {
                //μήνυμα στον χρήστη να διαλέξει ένα μοντέλο
                JOptionPane.showMessageDialog(null,"Please choose a model");
                jboxmodelChoice=null;
            }
            else
            {
                //διαχωρισμός του String έτσι ώστε να αποθηκευτoύν ξεχωριστά το όνομα του μοντέλου και η μάρκα
                String[] s=jboxmodelChoice.split(":");
                marka=s[0];
                jboxmodel=s[1];
            }
        }
    }//GEN-LAST:event_jComboBoxModelActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        //αφαίρεση προϊόντος από τη λίστα πώλησης
        int row=jTableOrder.getSelectedRow();
        //προσθήκη στη λίστα με τα διεγραμμένα προϊόντα του ονόματος του μοντέλου που διαγράφηκε
        String deletedModel=String.valueOf(jTableOrder.getValueAt(row, 2));
        deletedList.add(deletedModel);
        //σβήσιμο γραμμής
        lista.removeRow(row);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        //η λίστα με τα προϊόντα της παραγγελίας
        lista=(DefaultTableModel)jTableOrder.getModel();
        //αν δεν έγινε επιλογή από το jComboBox
        if(jboxmodel==null)
        {
            //αποθήκευση των επιλογών του χρήστη
            jTextBrand=jTextWriteBrand.getText();
            jTextModel=jTextWriteModel.getText();
            quantity=jTextItems.getText();
            //αν παρέληψε ο χρήστης να συμπληρώσει ένα πεδίο
            if(jTextBrand.isEmpty()||jTextModel.isEmpty())
                //μήνυμα στον χρήστη ότι δεν πρέπει να συμπληρώσει και τα δύο πεδία
                JOptionPane.showMessageDialog(null,"please fill in the fields or select model from combobox,not both of them!");
            else
            {
                jmodel=jTextModel;
                marka=jTextBrand;
                //αν έχουν συμπληρωθεί όλα τα υπόλοιπα πεδία
                if((jboxproduct!=null)&&(!quantity.isEmpty()))
                {
                    //προσθήκη γραμμής στο jTable
                    lista.addRow(new String[]{jboxproduct,marka,jmodel,quantity});
                    //προσθήκη του ονόματος του μοντέλλου και της ποσότητας στη λίστα της παραγγελίας
                    paraggelia=quantity+" item(s) of "+jboxproduct+", "+marka+" "+jmodel;
                    //η λίστα με τα ονόματα των προϊόντων
                    OrderList.add(paraggelia);
                }
                else
                    //μήνυμα στον χρήστη ότι δεν έχει συμπληρώσει όλα τα πεδία
                    JOptionPane.showMessageDialog(null,"please fill in all the fields and select model!");
            }
            //αρχικοποίηση των πεδίων για την επόμενη εγγραφή
            jTextBrand=null;
            jTextWriteBrand.setText(null);
            jTextModel=null;
            jTextWriteModel.setText(null);
            jComboBoxModel.removeAllItems();
            jTextItems.setText(null);
            quantity=null;
        }
        //αν έγινε επιλογή από το jComboBox
        if((jboxmodel!=null))
        {
            //αποθήκευση των επιλογών του χρήστη
            jTextBrand=jTextWriteBrand.getText();
            jTextModel=jTextWriteModel.getText();
            quantity=jTextItems.getText();
            //αν ο χρήστης επέλεξε μοντέλο από το combobox
            if(jTextBrand.isEmpty()&&jTextModel.isEmpty())            
            {
                jmodel=jboxmodel;
                
                //αν έχουν συμπληρωθεί όλα τα υπόλοιπα πεδία
                if((jboxproduct!=null)&&(!quantity.isEmpty()))
                {
                    //[ρπσθήκη γραμμής στο jTable
                    lista.addRow(new String[]{jboxproduct,marka,jboxmodel,quantity});
                    //προσθήκη του ονόματος του μοντέλλου και της ποσότητας στη λίστα της παραγγελίας
                    paraggelia=quantity+" item(s) of "+jboxproduct+", "+marka+" "+jmodel;
                    //η λίστα με τα ονόματα των προϊόντων
                    OrderList.add(paraggelia);
                }
                else
                //μήνυμα στον χρήστη ότι δεν έχει συμπληρώσει όλα τα πεδία
                JOptionPane.showMessageDialog(null,"please fill in all the fields and select model!");
            }
            else
                //μήνυμα στον χρήστη ότι δεν πρέπει να συμπληρώσει τα δύο πεδία
                JOptionPane.showMessageDialog(null,"please don't fill in the fields if you have select model from combobox!");
            //αρχικοποίηση των πεδίων για την επόμενη εγγραφή
            jTextBrand=null;
            jTextModel=null;
            jmodel=null;
            marka=null;
            jboxmodel=null;
            jComboBoxModel.removeAllItems();
            jTextItems.setText(null);
            quantity=null;
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductActionPerformed
        //αποθήκευση της επολογής του χρήστη
        String chooseItem=jComboBoxProduct.getSelectedItem().toString();
        if(chooseItem=="CATEGORY...")
        {
            //μήνυμα στον χρήστη να διαλέξει ένα μοντέλο
            JOptionPane.showMessageDialog(null,"Please choose a category");
            chooseItem=null;
        }
        else
        {
        //εύρεση του αντίστοιχου πίνακα της επιλογής του χρήστη
        jboxproduct= ordercon.getTheTableOrder(chooseItem);
        //καταχώρηση της λίστας του πίνακα που ζητήθηκε
        List<String> models = ordercon.getListaOrderCon(jboxproduct);
        if(models.isEmpty())
            //μήνυμα στον χρήστη ότι δεν έχει βρεθεί η λίστα με μοντέλα
            JOptionPane.showMessageDialog(null,"No list of models have found!Please try again! ");
        //το πρώτο στοιχείο της λίστας
        models.add(0, "MODELS...");
        //διαγραφή της λίστας από προηγούμενη επιλογή
        if(jComboBoxModel.getItemCount()>0)
            jComboBoxModel.removeAllItems();
        //δημιουργία λίστας με τα μοντέλα της νέας επιλογής
        for(String a:models)
        {
            jComboBoxModel.addItem(a);
        }
        //αρχικοποίηση της μεταβλητής που αποθηκεύει την επιλογή από το jComboBox
        jboxmodel=null;
        }
    }//GEN-LAST:event_jComboBoxProductActionPerformed

    private void jTextItemsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextItemsKeyTyped
        //έλεγχος εισόδου από το πληκτρολόγιο να είναι μόνο νούμερα
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextItemsKeyTyped

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        //μεταβλητή που θα χρησιμοποιηθεί για την συμπλήρωση της λίστας OrderString
        OrderString orderstring=new OrderString();
        DefaultTableModel tableRow=(DefaultTableModel)jTableOrder.getModel();
        if(jTableOrder.getRowCount()==0)
            //μήνυμα στον χρήστη ότι δεν έχει συμπληρώσει όλα τα πεδία
            JOptionPane.showMessageDialog(null,"please fill in your id and add items in the list");
        else
        {
            /*η παραγγελία που θα πραγματοποιηθεί με ορίσματα τον προϊστάμενο
            που καταχωρεί την παραγγελία και τη λίστα με τα προϊόντα*/
            Order orderCreated=new Order((ProductManager) ipallilos,OrderModelList);
            //ενημέρωση της λίστας  με τα διεγραμμένα προϊόντα
            for(String d:OrderList)
            {
                //αν είναι διεγραμμένο προίόν
                for(String f:deletedList)
                {
                    if(d.endsWith(f))
                        finaDeletedlList.add(d);
                }                  
            }
            for(String d:OrderList)
            {
                //αν δεν είναι διεγραμμένο προϊόν
                if(!finaDeletedlList.contains(d))
                {
                    //προσθήκη στην τελική λίστα με τα προϊόντα της παραγγελίας
                    OrderString orderstring1=new OrderString();
                    orderstring1.setProin(d);                   
                    OrderModelList.add(orderstring1);
                }
            }         
            //προσθήκη της παραγγελίας σε κάθε OrderString
            for(OrderString a:OrderModelList)
            {
                a.setOrderProin(orderCreated);
            }
                
            //αποθήκευση στη βάση της παραγγελίας και των OrderString με τα αντίστοιχ αμηνύματα ενημέρωσης στον χρήστη
            if(ordercon.saveOrder(orderCreated))
            {
                JOptionPane.showMessageDialog(null,"The order has been saved in the database!");                
                for(OrderString a:OrderModelList)
                    saved=a.saveOrdString();
                    if(!saved)
                        JOptionPane.showMessageDialog(null,"The database hasn't been updated!");     
            }               
            else
                JOptionPane.showMessageDialog(null,"The order hasn t been saved.Please try again!");
            //αρχικοποίηση μεταβλητών
            jTextItems.setText(null);
            jboxmodelChoice=null;
            for(int i=0;i<jTableOrder.getRowCount();i++)
                lista.removeRow(i);
            //διαγραφή της λίστας από προηγούμενη επιλογή
            if(jComboBoxModel.getItemCount()>0)
                jComboBoxModel.removeAllItems();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderCreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderCreateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboBoxProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField jTextItems;
    private javax.swing.JTextField jTextWriteBrand;
    private javax.swing.JTextField jTextWriteModel;
    // End of variables declaration//GEN-END:variables
}
