
package VIEW;

import CONTROLLER.SaleCon;
import MODEL.ProductString;
import MODEL.Sale;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SaleShowView extends javax.swing.JFrame {

    /**
     * Creates new form SaleView
     */
    public SaleShowView() {
        initComponents();
        //display on the center of the screen
        this.setLocationRelativeTo(null);
    }
    
    //variables for the date
    private String year;
    private String day;
    private String month;
    private String date;
    //the next day of the chosen date
    private String date2;
    //variables for the jTableSaleShow
    private String imerominia;
    private String pelatis;
    private String poso;
    //instance of CONTROLLER for its methods
    SaleCon salecon=new SaleCon();
    //instance of SALE for its methods
    Sale saleShow=new Sale();
    /*the attributes of the employee
    the first values which will appear on the screen before the search*/
    String epithetoEmployee="NOT FOUND";
    String onomaEmployee="YET";
    /*the attributes of the customer
    the first values which will appear on the screen before the search*/
    String epithetoCustomer="NOT FOUND";
    String onomaCustomer="YET";
    //the sale list
    ArrayList <Sale> saleLista=new ArrayList <Sale>();
    //the list of the products of the sale
    ArrayList <ProductString> productLista=new ArrayList <ProductString>();
    //the list for the jTableSaleShow
    DefaultTableModel polisis;
    //the list for the jTableProdustsShow
    DefaultTableModel proionta;
    //the date of the sale
    Date datep;
    //the next day of the sale
    Date dates;
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextYear = new javax.swing.JTextField();
        jTextMonth = new javax.swing.JTextField();
        jTextDay = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSaleShow = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelCustomer = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelEmployee = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdustsShow = new javax.swing.JTable();
        jButtonShowSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SHOW SALE");

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setText("DATE:");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("Year");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("Day");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setText("Month");

        jTextYear.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextYearKeyTyped(evt);
            }
        });

        jTextMonth.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMonthKeyTyped(evt);
            }
        });

        jTextDay.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTextDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDayKeyTyped(evt);
            }
        });

        jTableSaleShow.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jTableSaleShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "CUSTOMER", "TOTAL PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableSaleShow.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTableSaleShow);
        jTableSaleShow.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("            Sale Search ");
        jLabel1.setToolTipText("");

        jButtonSearch.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSearch.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonSearch.setText("SEARCH");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Customer");

        jLabelCustomer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabelCustomer.setText(epithetoCustomer+" "+onomaCustomer);
        jLabelCustomer.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Employee");

        jLabelEmployee.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabelEmployee.setText(epithetoEmployee+" "+onomaEmployee);
        jLabelEmployee.setToolTipText("");

        jTableProdustsShow.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jTableProdustsShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SALE LIST"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProdustsShow.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(jTableProdustsShow);
        jTableProdustsShow.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButtonShowSale.setBackground(new java.awt.Color(102, 102, 255));
        jButtonShowSale.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButtonShowSale.setText("SHOW SALE");
        jButtonShowSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jTextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonShowSale, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addGap(17, 17, 17)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowSale, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextYearKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextYearKeyTyped

    private void jTextMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMonthKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextMonthKeyTyped

    private void jTextDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDayKeyTyped
        //check if the input of the user is a digit
        char typeKey=evt.getKeyChar();
        if(!((Character.isDigit(typeKey)||(typeKey=='\b'))))
        {
            JOptionPane.showMessageDialog(this, "please insert a digit");
            evt.consume();
        }
    }//GEN-LAST:event_jTextDayKeyTyped

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        //inputs of the user
        day=jTextDay.getText();
        month=jTextMonth.getText();
        year=jTextYear.getText();
        //the next day of the input day
        String day2=String.valueOf(Integer.parseInt(day)+1);
        //check the year
        if(year.length()!=4)
            JOptionPane.showMessageDialog(this, "please insert four digits for the year");
        //check the day
        else if(Integer.parseInt(day)>31)
            JOptionPane.showMessageDialog(this, "there is not such a day in a month.Please try again!");
        //check the month
        else if(Integer.parseInt(month)>12)
            JOptionPane.showMessageDialog(this, "there is not such a month in a year.Please try again!");
        else
        {
            //save the date as a string
            date=year+"-"+month+"-"+day;
            //the next day of the date of the sale
            date2=year+"-"+month+"-"+day2;
            try 
            {
                datep=new SimpleDateFormat("yyyy-MM-dd").parse(date);
                dates=new SimpleDateFormat("yyyy-MM-dd").parse(date2);
            } 
            catch (ParseException ex) {
                Logger.getLogger(StatisticsShowView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //search for the sales of the date
        saleLista=salecon.findSaleList(datep,dates);
        //if there is no sales
        if(saleLista==null)
        {
            JOptionPane.showMessageDialog(this, "there is not a sale in that date.Please try again!");
            //reset the fields
            jTextDay.setText(null);
            jTextMonth.setText(null);
            jTextYear.setText(null);
            date=null;
            date2=null;
        }
        //if there are sales on that date
        else
        {
            //the list for the jTable
            polisis=(DefaultTableModel)jTableSaleShow.getModel();
            for(Sale s:saleLista)
            {
                imerominia=s.getSerialNumber();
                pelatis=s.getCustomer().getSurname()+" "+s.getCustomer().getName();
                poso=String.valueOf(s.getTotalPrice());
                //add a line with a sale on the jTable
                polisis.addRow(new String[]{imerominia,pelatis,poso});
            }
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonShowSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowSaleActionPerformed
        //the number of the selected row
        int row=jTableSaleShow.getSelectedRow();
        //the serialnumber of the selected sale
        String epilogi=String.valueOf(jTableSaleShow.getValueAt(row, 0));
        //search of the sale
        Sale polisi=salecon.findSale(epilogi);
        //if there is no sale
        if(polisi==null)
            JOptionPane.showMessageDialog(this, "there is a problem with that sale in the base.Please try again!");
        else
        {
            //the name and the surname of the employee who had made the sale
            epithetoEmployee=polisi.getUser().getSurname();
            onomaEmployee=polisi.getUser().getName();
            //display on the screen
            jLabelEmployee.setText(epithetoEmployee+" "+onomaEmployee);
            //the name and the surname of the customer of the sale
            epithetoCustomer=polisi.getCustomer().getSurname();
            onomaCustomer=polisi.getCustomer().getName();
            //display on the screen
            jLabelCustomer.setText(epithetoCustomer+" "+onomaCustomer);
        }   
        productLista=salecon.findProducts(epilogi);
        //the list for the jTable
        proionta=(DefaultTableModel)jTableProdustsShow.getModel();
        //the name of the model
        String onomaPro;
        for(ProductString p:productLista)
        {
           onomaPro=p.getProin();
           //add the model on the lne of the jTable
           proionta.addRow(new String[]{onomaPro});            
        }    
    }//GEN-LAST:event_jButtonShowSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleShowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleShowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleShowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleShowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleShowView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonShowSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCustomer;
    private javax.swing.JLabel jLabelEmployee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableProdustsShow;
    private javax.swing.JTable jTableSaleShow;
    private javax.swing.JTextField jTextDay;
    private javax.swing.JTextField jTextMonth;
    private javax.swing.JTextField jTextYear;
    // End of variables declaration//GEN-END:variables
}
